#!/bin/bash
for i in {1..4}
do
for((sp=4-$i;sp>0;sp=sp-1))
do
echo -n " "
done
for((j=1;j<=i;j=j+1))
do
echo -n "* "
done
echo
done
for((i=4;i>=0;i=i-1))
do
for((sp=4-$i;sp>0;sp=sp-1))
do
echo -n " "
done
for((j=1;j<=i;j=j+1))
do
echo -n "* "
done
echo
done

